### PR TITLE
Feature/series graphic

### LINKED ISSUE #139: choose series image
the ability to choose an image for a series, not just for the podcast itself.

ref: https://wordpress.org/support/topic/amazing-plugin-one-major-thing-missing-images-for-series/

### PR DESCRIPTION
**Pull request by timnolte**
## Summary

This PR can be summarized in the following changelog entry:

* Adds a protected text domain unique identifier attribute to the admin class. Changes uses of the string found in the admin class to use the new protected attribute.
* Adds a metabox to the Series term add/edit forms for attaching an image to a series.
* Enqueues the WordPress media library editor only for the Series term add/edit forms.
* Adds a series image thumbnail to the series term list.

## Relevant technical choices:

* Changed the text domain strings to using a protected class attribute to ensure consistent use in future development.
* A default series display only image has been included as a placeholder only, presented when no series image has been assigned.
* No changes were made to podcast feeds or Series listings to present the series image at this time. Further uses, requiring additional code changes, need to be confirmed with the plugin maintainers.

## Test instructions

This PR can be tested by following these steps:

* New series:
  1. Add a new Series.
  2. Click new "Add Image" button.
  3. Upload and/or choose an image.
  4. Save the series and confirm editing and saving still work as expected.

* Edit an existing Series:
  1. Choose "Edit" on an existing Series entry.
  2. Upload or change the Series image.
  3. Update the chosen Series and confirm the series graphic is presenting as expected.

Fixes #139

### CODE REVIEW

**Comment by jonathanbossenger** [comment]
@timnolte as I've been merging previous PRs into develop there are now a couple of conflicts with this one. Could I ask you to resolve them and then I can continue with reviewing/merging. Thanks

**Comment by timnolte** [comment]
@jonathanbossenger resolved the conflicts and the PR should be ready to merge. Sorry for the delay! Thanks!

**Comment by jonathanbossenger** [comment]
@timnolte no problems, thanks for the update.

We probably won't get this one reviewed in time for the next plugin release, but I'll make sure its included in the following one.

**Comment by timnolte** [comment]
@jonathanbossenger no worries. There is still a little more work that probably needs to be done once you've had a chance to review it. Thanks!

**Comment by jonathanbossenger** [comment]
Hi @timnolte sorry to be a pain, but it seems that with latest developments there is another conflict. If I could ask you to review and fix that. Thanks

**Comment by timnolte** [comment]
@jonathanbossenger conflicts resolved once again. Hoping this gets easier. Since I use CodeAnywhere my only diff tool is vimdiff which takes a little getting used to. I don't easily trust my resolutions in vimdiff. Thanks!

**Comment by jonathanbossenger** [comment]
@timnolte thanks very much. We're in the final stages of a big plugin update planned for next week, once that is completed I'll be able to give this a proper review to be included in the next release. Thanks for your work on this and your patience in getting it merged in.

**Comment by jonathanbossenger** [comment]
Thanks @timnolte we've merged this into a release candidate for testing/consideration into our next release.

**Comment by timnolte** [comment]
@jonathanbossenger thanks. There really is some more work to be done as I still needed some more direction on how users will want to use the attached image. Let me know your thoughts and I can submit another PR after the release to further enhance.

**Pull request merged**
