### PR TITLE
Update class_ssp_shortcode_ss_player.php

### PR DESCRIPTION
**Pull request by robertogcalle**
Make use of the ss_podcasting_player_style global option for displaying player.
Related to the issue #295

### CODE REVIEW

**Comment by jonathanbossenger** [comment]
Hi @robertogcalle thanks for the PR.

Could I ask you to update the PR to submit it against the _develop_ branch, as per the [contributing guidelines](https://github.com/thecraighewitt/Seriously-Simple-Podcasting/blob/master/CONTRIBUTING.md).

Thanks

**Comment by robertogcalle** [comment]
Done.

**Comment by jonathanbossenger** [comment]
Thanks @robertogcalle. One last thing, would you mind updating the `get_option` call to include a default return value of an empty string. Than I'm happy to merge it.

**Comment by jonathanbossenger** [comment]
Thank you.

**Pull request merged**
