### PR TITLE
Make SSP player accessible to screen readers

### PR DESCRIPTION
**Pull request by itmaybejj**
As per:
https://github.com/TheCraigHewitt/Seriously-Simple-Podcasting/issues/312

Added:
- CSS for hover and focus on interactive elements
- aria labels and tabindex attributes for interactive elements
- JS handlers for keyboard interactions with buttons

(this is all for the Large Player; I'm sure the playlist player needs similar things, but I've got to get back to other things).

### CODE REVIEW

**Comment by itmaybejj** [comment]
Oh bother; since I worked from the master branch this includes cruft from Master being behind Develop. If you'd like me to recreate it without that just asked; otherwise just cherry-pick my commit.

**Comment by jonathanbossenger** [comment]
@itmaybejj thanks.

I will do my best to get get this PR merged before the end of Hacktoberfest, if you are taking part ;-) with an aim to have it included in our 1.19.14 release.

**Comment by itmaybejj** [comment]
Yay! 

And no Hacktoberfest; just loving the plugin and giving back a little.

**Comment by jonathanbossenger** [comment]
Hi @itmaybejj since our last chat there have been some other minor bugs fixed and merged into develop, which are now causing a few conflicts with your branch. Could I ask you to resolve these conflicts, so that I Can get this merged into the next release. Thanks

**Comment by itmaybejj** [comment]
better?

**Comment by jonathanbossenger** [comment]
@itmaybejj perfect thank you.

**Comment by jonathanbossenger** [comment]
@itmaybejj in testing this code, it introduces a bug, in that the HTML5 player no longer plays the audio files.

Can I ask you to recreate this pull request, so that we can create a separate testing branch, in order to test and fix any bugs related to this update.

I'd be really happy if we can get this implemented, but not at the expense of the functionality of the player code. 

Thanks

**Comment by itmaybejj** [comment]
Eww that's no good. Will do.

**Pull request merged**
