### PR TITLE
WP Datepicker Styling

### LINKED ISSUE #132: Consider including WP Datepicker Styling
If you have a content security policy that doesn't allow inclusion of remote scripts, the Smoothness jQuery theme won't be accessible, and there is no local fallback.

screen shot 2017-01-12 at 4 28 53 pm

Not ironically, I have a solution to this problem: https://github.com/stuttter/wp-datepicker-styling

I think it makes the most sense here to bundle styling that more closely matches `wp-admin` vs. relying on an external library.

### PR DESCRIPTION
**Pull request by timnolte**
This implements the datepicker WordPress styles developed by @stuttter and recommended by @jjj which fixes #132

### CODE REVIEW

**Comment by jonathanbossenger** [comment]
Thanks @timnolte I will review the PR during the course of this week.

**Comment by timnolte** [comment]
Any feedback on this? You need me to make any changes in order for you to accept the PR? Thanks!

**Comment by jonathanbossenger** [comment]
Sorry @timnolte I've been busy pushing other developments. We'll be rolling out another plugin update soon and I'll make sure to review this PR as part of that process.

**Comment by timnolte** [comment]
@jonathanbossenger no worries I understand. Thanks for the update!

**Pull request merged**
